<<<<<<< HEAD
title: "Icelandic Lifting Stones"
theme: jekyll-theme-minimal
=======
<<<<<<< HEAD
title: "Icelandic Lifting Stones"
=======
>>>>>>> cfce37e345438da99e5300a550d5a312d7d5d3fe
theme: jekyll-theme-cayman
>>>>>>> ff50549fab6b7f0b58207dd989966d8dd513dc21
